/** Argentina — Provincia → Localidad/Ciudad[] for COD checkout */
export type ArgentinaGeoTree = Record<string, string[]>;

export const GEO_AR: ArgentinaGeoTree = {
  "Buenos Aires": [
    "9 de Julio",
    "Adrogué",
    "Avellaneda",
    "Azul",
    "Bahía Blanca",
    "Balcarce",
    "Banfield",
    "Belén de Escobar",
    "Benavídez",
    "Berazategui",
    "Boulogne",
    "Bragado",
    "Campana",
    "Castelar",
    "Chascomús",
    "Chivilcoy",
    "Ciudad Evita",
    "Coronel Suárez",
    "Del Viso",
    "Dolores",
    "Don Torcuato",
    "El Talar",
    "Escobar",
    "Ezeiza",
    "Florencio Varela",
    "Garín",
    "General Pacheco",
    "General Rodríguez",
    "González Catán",
    "Gregorio de Laferrere",
    "Haedo",
    "Hurlingham",
    "Ingeniero Maschwitz",
    "Isidro Casanova",
    "Ituzaingó",
    "José C. Paz",
    "José León Suárez",
    "Junín",
    "La Matanza",
    "La Plata",
    "Lanús",
    "Lincoln",
    "Lobos",
    "Lomas de Zamora",
    "Luján",
    "Malvinas Argentinas",
    "Mar Chiquita",
    "Mar del Plata",
    "Mercedes",
    "Merlo",
    "Miramar",
    "Moreno",
    "Morón",
    "Morón Centro",
    "Necochea",
    "Olavarría",
    "Pehuajó",
    "Pergamino",
    "Pilar",
    "Pinamar",
    "Quilmes",
    "Rafael Castillo",
    "Ramos Mejía",
    "San Fernando",
    "San Isidro",
    "San Justo",
    "San Martín",
    "San Miguel",
    "San Nicolás",
    "San Pedro",
    "Tandil",
    "Temperley",
    "Tigre",
    "Tres Arroyos",
    "Tres de Febrero",
    "Vicente López",
    "Villa Ballester",
    "Villa Gesell",
    "Zárate"
  ],
  "CABA": [
    "Agronomía",
    "Almagro",
    "Balvanera",
    "Barracas",
    "Belgrano",
    "Boedo",
    "Caballito",
    "Chacarita",
    "Coghlan",
    "Colegiales",
    "Constitución",
    "Flores",
    "Floresta",
    "La Boca",
    "Liniers",
    "Mataderos",
    "Monserrat",
    "Monte Castro",
    "Nueva Pompeya",
    "Núñez",
    "Palermo",
    "Parque Avellaneda",
    "Parque Chacabuco",
    "Parque Chas",
    "Parque Patricios",
    "Paternal",
    "Puerto Madero",
    "Recoleta",
    "Recoleta Norte",
    "Retiro",
    "Saavedra",
    "San Cristóbal",
    "San Telmo",
    "Versalles",
    "Villa Crespo",
    "Villa del Parque",
    "Villa Devoto",
    "Villa General Mitre",
    "Villa Lugano",
    "Villa Luro",
    "Villa Ortúzar",
    "Villa Pueyrredón",
    "Villa Riachuelo",
    "Villa Santa Rita",
    "Villa Soldati",
    "Villa Urquiza"
  ],
  "Catamarca": [
    "Andalgalá",
    "Belén",
    "Capayán",
    "Fiambalá",
    "Pomán",
    "Recreo",
    "San Fernando del Valle de Catamarca",
    "Santa María",
    "Tinogasta",
    "Valle Viejo"
  ],
  "Chaco": [
    "Barranqueras",
    "Castelli",
    "Charata",
    "Fontana",
    "General San Martín",
    "Juan José Castelli",
    "Las Breñas",
    "Machagai",
    "Presidencia Roque Sáenz Peña",
    "Quitilipi",
    "Resistencia",
    "Villa Ángela"
  ],
  "Chubut": [
    "Comodoro Rivadavia",
    "Dolavon",
    "Esquel",
    "Gaiman",
    "Puerto Madryn",
    "Rada Tilly",
    "Rawson",
    "Sarmiento",
    "Trelew",
    "Trevelin"
  ],
  "Córdoba": [
    "Alta Gracia",
    "Arroyito",
    "Bell Ville",
    "Córdoba Capital",
    "Cosquín",
    "Cruz del Eje",
    "Jesús María",
    "La Calera",
    "Laboulaye",
    "Marcos Juárez",
    "Mina Clavero",
    "Morteros",
    "Río Cuarto",
    "Río Tercero",
    "San Francisco",
    "Unquillo",
    "Villa Allende",
    "Villa Carlos Paz",
    "Villa Dolores",
    "Villa María"
  ],
  "Corrientes": [
    "Bella Vista",
    "Corrientes Capital",
    "Curuzú Cuatiá",
    "Empedrado",
    "Esquina",
    "Goya",
    "Ituzaingó",
    "Mercedes",
    "Monte Caseros",
    "Paso de los Libres",
    "Saladas",
    "Santo Tomé"
  ],
  "Entre Ríos": [
    "Chajarí",
    "Colón",
    "Concepción del Uruguay",
    "Concordia",
    "Crespo",
    "Diamante",
    "Federación",
    "Gualeguay",
    "Gualeguaychú",
    "La Paz",
    "Nogoyá",
    "Paraná",
    "Victoria",
    "Villaguay"
  ],
  "Formosa": [
    "Clorinda",
    "Comandante Fontana",
    "El Colorado",
    "Formosa Capital",
    "Ibarreta",
    "Laguna Blanca",
    "Las Lomitas",
    "Pirané"
  ],
  "Jujuy": [
    "El Carmen",
    "Humahuaca",
    "La Quiaca",
    "Libertador General San Martín",
    "Monterrico",
    "Palpalá",
    "Perico",
    "San Pedro de Jujuy",
    "San Salvador de Jujuy",
    "Tilcara"
  ],
  "La Pampa": [
    "Eduardo Castex",
    "General Acha",
    "General Pico",
    "Intendente Alvear",
    "Macachín",
    "Realicó",
    "Santa Rosa",
    "Toay",
    "Victorica"
  ],
  "La Rioja": [
    "Aimogasta",
    "Chamical",
    "Chepes",
    "Chilecito",
    "Famatina",
    "La Rioja Capital",
    "Nonogasta",
    "Ulapes",
    "Villa Unión"
  ],
  "Mendoza": [
    "General Alvear",
    "Godoy Cruz",
    "Guaymallén",
    "Junín",
    "Las Heras",
    "Lavalle",
    "Luján de Cuyo",
    "Maipú",
    "Malargüe",
    "Mendoza Capital",
    "Rivadavia",
    "San Martín",
    "San Rafael",
    "Tunuyán",
    "Tupungato"
  ],
  "Misiones": [
    "Apóstoles",
    "Aristóbulo del Valle",
    "Eldorado",
    "Jardín América",
    "Leandro N. Alem",
    "Montecarlo",
    "Oberá",
    "Posadas",
    "Puerto Iguazú",
    "Puerto Rico",
    "San Vicente",
    "Wanda"
  ],
  "Neuquén": [
    "Añelo",
    "Centenario",
    "Chos Malal",
    "Cutral Có",
    "Neuquén Capital",
    "Plaza Huincul",
    "Plottier",
    "Rincón de los Sauces",
    "San Martín de los Andes",
    "Villa La Angostura",
    "Zapala"
  ],
  "Río Negro": [
    "Allen",
    "Bariloche",
    "Catriel",
    "Choele Choel",
    "Cinco Saltos",
    "Cipolletti",
    "El Bolsón",
    "General Roca",
    "Las Grutas",
    "Río Colorado",
    "San Antonio Oeste",
    "Viedma",
    "Villa Regina"
  ],
  "Salta": [
    "Cafayate",
    "Cerrillos",
    "El Carmen",
    "Embarcación",
    "General Güemes",
    "Joaquín V. González",
    "Metán",
    "Orán",
    "Pichanal",
    "Rosario de Lerma",
    "Salta Capital",
    "San Lorenzo",
    "Tartagal"
  ],
  "San Juan": [
    "Albardón",
    "Calingasta",
    "Caucete",
    "Chimbas",
    "Iglesia",
    "Jáchal",
    "Pocito",
    "Rawson",
    "Rivadavia",
    "San Juan Capital",
    "Santa Lucía",
    "Valle Fértil"
  ],
  "San Luis": [
    "Concarán",
    "Justo Daract",
    "La Punta",
    "Merlo",
    "Quines",
    "San Luis Capital",
    "Tilisarao",
    "Villa de Merlo",
    "Villa Mercedes"
  ],
  "Santa Cruz": [
    "Caleta Olivia",
    "El Calafate",
    "El Chaltén",
    "Las Heras",
    "Perito Moreno",
    "Pico Truncado",
    "Puerto Deseado",
    "Puerto San Julián",
    "Puerto Santa Cruz",
    "Río Gallegos"
  ],
  "Santa Fe": [
    "Capitán Bermúdez",
    "Casilda",
    "Esperanza",
    "Firmat",
    "Funes",
    "Gálvez",
    "Pérez",
    "Rafaela",
    "Reconquista",
    "Roldán",
    "Rosario",
    "Rufino",
    "San Lorenzo",
    "Santa Fe Capital",
    "Santo Tomé",
    "Sunchales",
    "Venado Tuerto",
    "Villa Constitución",
    "Villa Gobernador Gálvez"
  ],
  "Santiago del Estero": [
    "Añatuya",
    "Fernández",
    "Frías",
    "La Banda",
    "Loreto",
    "Monte Quemado",
    "Santiago del Estero",
    "Suncho Corral",
    "Termas de Río Hondo",
    "Villa Ojo de Agua"
  ],
  "Tierra del Fuego": [
    "Río Grande",
    "Tolhuin",
    "Ushuaia"
  ],
  "Tucumán": [
    "Aguilares",
    "Banda del Río Salí",
    "Concepción",
    "Famaillá",
    "Juan Bautista Alberdi",
    "Lules",
    "Monteros",
    "San Miguel de Tucumán",
    "Simoca",
    "Tafí del Valle",
    "Tafí Viejo",
    "Yerba Buena"
  ]
};

export function argentinaProvincias(): string[] {
  return Object.keys(GEO_AR).sort((a, b) => a.localeCompare(b, "es"));
}

export function argentinaLocalidades(provincia: string): string[] {
  return GEO_AR[provincia] ?? [];
}
