import type { CountryCode } from "./types";

export type GeoDivision = {
  name: string;
  cities: string[];
};

function cities(...list: string[]): string[] {
  return list;
}

/** First-level divisions + main cities Fufills covers for COD checkout */
export const CHECKOUT_GEO: Record<CountryCode, GeoDivision[]> = {
  MA: [
    {
      name: "Maroc",
      cities: cities(
        "Casablanca",
        "Rabat",
        "Salé",
        "Marrakech",
        "Fès",
        "Tanger",
        "Agadir",
        "Meknès",
        "Oujda",
        "Kénitra",
        "Tétouan",
        "Safi",
        "El Jadida",
        "Nador",
        "Béni Mellal",
        "Mohammedia",
        "Khouribga",
        "Settat",
        "Larache",
        "Essaouira"
      ),
    },
  ],
  SA: [
    {
      name: "السعودية",
      cities: cities(
        "الرياض",
        "جدة",
        "مكة",
        "المدينة المنورة",
        "الدمام",
        "الخبر",
        "الظهران",
        "الطائف",
        "تبوك",
        "أبها",
        "خميس مشيط",
        "حائل",
        "بريدة",
        "الجبيل",
        "ينبع",
        "نجران",
        "جازان",
        "الأحساء"
      ),
    },
  ],
  AE: [
    {
      name: "الإمارات",
      cities: cities(
        "دبي",
        "أبوظبي",
        "الشارقة",
        "عجمان",
        "رأس الخيمة",
        "الفجيرة",
        "أم القيوين",
        "العين"
      ),
    },
  ],
  OM: [
    {
      name: "عُمان",
      cities: cities("مسقط", "صلالة", "صحار", "نزوى", "صور", "البريمي", "عبري"),
    },
  ],
  IQ: [
    {
      name: "العراق",
      cities: cities(
        "بغداد",
        "البصرة",
        "أربيل",
        "الموصل",
        "النجف",
        "كربلاء",
        "السليمانية",
        "كركوك",
        "الحلة",
        "الناصرية"
      ),
    },
  ],
  LY: [
    {
      name: "ليبيا",
      cities: cities(
        "طرابلس",
        "بنغازي",
        "مصراتة",
        "البيضاء",
        "الزاوية",
        "طبرق",
        "سبها",
        "زليتن"
      ),
    },
  ],
  LB: [
    {
      name: "لبنان",
      cities: cities(
        "بيروت",
        "طرابلس",
        "صيدا",
        "صور",
        "جونية",
        "زحلة",
        "بعلبك",
        "النبطية"
      ),
    },
  ],
  KW: [{ name: "الكويت", cities: cities("الكويت", "حولي", "الفروانية", "الجهراء", "الأحمدي") }],
  BH: [{ name: "البحرين", cities: cities("المنامة", "المحرق", "الرفاع", "عيسى") }],
  QA: [{ name: "قطر", cities: cities("الدوحة", "الريان", "الوكرة", "الخور") }],
  EG: [
    {
      name: "مصر",
      cities: cities(
        "القاهرة",
        "الجيزة",
        "الإسكندرية",
        "المنصورة",
        "طنطا",
        "أسيوط",
        "بورسعيد",
        "السويس",
        "شرم الشيخ"
      ),
    },
  ],
  US: [
    { name: "California", cities: cities("Los Angeles", "San Diego", "San Francisco", "San Jose") },
    { name: "Texas", cities: cities("Houston", "Dallas", "Austin", "San Antonio") },
    { name: "Florida", cities: cities("Miami", "Orlando", "Tampa", "Jacksonville") },
    { name: "New York", cities: cities("New York", "Buffalo", "Rochester") },
  ],
  MX: [
    { name: "Aguascalientes", cities: cities("Aguascalientes") },
    { name: "Baja California", cities: cities("Tijuana", "Mexicali", "Ensenada") },
    { name: "Baja California Sur", cities: cities("La Paz", "Los Cabos") },
    { name: "Campeche", cities: cities("Campeche", "Ciudad del Carmen") },
    { name: "Chiapas", cities: cities("Tuxtla Gutiérrez", "Tapachula", "San Cristóbal de las Casas") },
    { name: "Chihuahua", cities: cities("Chihuahua", "Ciudad Juárez") },
    {
      name: "Ciudad de México",
      cities: cities(
        "Álvaro Obregón",
        "Benito Juárez",
        "Coyoacán",
        "Cuauhtémoc",
        "Gustavo A. Madero",
        "Iztapalapa",
        "Miguel Hidalgo",
        "Tlalpan"
      ),
    },
    { name: "Coahuila", cities: cities("Saltillo", "Torreón", "Monclova") },
    { name: "Colima", cities: cities("Colima", "Manzanillo") },
    { name: "Durango", cities: cities("Durango", "Gómez Palacio") },
    {
      name: "Estado de México",
      cities: cities("Toluca", "Ecatepec", "Naucalpan", "Tlalnepantla", "Nezahualcóyotl"),
    },
    { name: "Guanajuato", cities: cities("León", "Guanajuato", "Irapuato", "Celaya") },
    { name: "Guerrero", cities: cities("Acapulco", "Chilpancingo", "Iguala") },
    { name: "Hidalgo", cities: cities("Pachuca", "Tulancingo") },
    {
      name: "Jalisco",
      cities: cities("Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Puerto Vallarta"),
    },
    { name: "Michoacán", cities: cities("Morelia", "Uruapan", "Zamora") },
    { name: "Morelos", cities: cities("Cuernavaca", "Jiutepec") },
    { name: "Nayarit", cities: cities("Tepic", "Bahía de Banderas") },
    {
      name: "Nuevo León",
      cities: cities("Monterrey", "San Pedro Garza García", "Guadalupe", "Apodaca", "San Nicolás de los Garza"),
    },
    { name: "Oaxaca", cities: cities("Oaxaca de Juárez", "Salina Cruz") },
    { name: "Puebla", cities: cities("Puebla", "Tehuacán") },
    { name: "Querétaro", cities: cities("Santiago de Querétaro", "San Juan del Río") },
    { name: "Quintana Roo", cities: cities("Cancún", "Playa del Carmen", "Chetumal") },
    { name: "San Luis Potosí", cities: cities("San Luis Potosí", "Ciudad Valles") },
    { name: "Sinaloa", cities: cities("Culiacán", "Mazatlán", "Los Mochis") },
    { name: "Sonora", cities: cities("Hermosillo", "Ciudad Obregón", "Nogales") },
    { name: "Tabasco", cities: cities("Villahermosa") },
    { name: "Tamaulipas", cities: cities("Reynosa", "Matamoros", "Tampico", "Nuevo Laredo") },
    { name: "Tlaxcala", cities: cities("Tlaxcala") },
    { name: "Veracruz", cities: cities("Veracruz", "Xalapa", "Coatzacoalcos", "Poza Rica") },
    { name: "Yucatán", cities: cities("Mérida") },
    { name: "Zacatecas", cities: cities("Zacatecas", "Fresnillo") },
  ],
  GT: [
    { name: "Guatemala", cities: cities("Guatemala City", "Mixco", "Villa Nueva", "Santa Catarina Pinula") },
    { name: "Quetzaltenango", cities: cities("Quetzaltenango") },
    { name: "Sacatepéquez", cities: cities("Antigua Guatemala") },
    { name: "Escuintla", cities: cities("Escuintla", "Santa Lucía Cotzumalguapa") },
    { name: "Huehuetenango", cities: cities("Huehuetenango") },
    { name: "Alta Verapaz", cities: cities("Cobán") },
    { name: "Petén", cities: cities("Flores", "Santa Elena") },
    { name: "Izabal", cities: cities("Puerto Barrios") },
    { name: "Chimaltenango", cities: cities("Chimaltenango") },
    { name: "Suchitepéquez", cities: cities("Mazatenango") },
    { name: "San Marcos", cities: cities("San Marcos") },
    { name: "Quiché", cities: cities("Santa Cruz del Quiché") },
    { name: "Jalapa", cities: cities("Jalapa") },
    { name: "Jutiapa", cities: cities("Jutiapa") },
    { name: "Santa Rosa", cities: cities("Cuilapa") },
    { name: "Sololá", cities: cities("Sololá", "Panajachel") },
    { name: "Totonicapán", cities: cities("Totonicapán") },
    { name: "Retalhuleu", cities: cities("Retalhuleu") },
    { name: "Chiquimula", cities: cities("Chiquimula") },
    { name: "Zacapa", cities: cities("Zacapa") },
    { name: "El Progreso", cities: cities("Guastatoya") },
    { name: "Baja Verapaz", cities: cities("Salamá") },
  ],
  HN: [
    { name: "Francisco Morazán", cities: cities("Tegucigalpa", "Comayagüela") },
    { name: "Cortés", cities: cities("San Pedro Sula", "Choloma", "Puerto Cortés") },
    { name: "Atlántida", cities: cities("La Ceiba", "Tela") },
    { name: "Yoro", cities: cities("El Progreso", "Yoro") },
    { name: "Comayagua", cities: cities("Comayagua") },
    { name: "Choluteca", cities: cities("Choluteca") },
    { name: "Olancho", cities: cities("Juticalpa") },
    { name: "Copán", cities: cities("Santa Rosa de Copán") },
    { name: "Santa Bárbara", cities: cities("Santa Bárbara") },
    { name: "Colón", cities: cities("Trujillo") },
    { name: "El Paraíso", cities: cities("Danlí") },
    { name: "Valle", cities: cities("Nacaome") },
    { name: "La Paz", cities: cities("La Paz") },
    { name: "Intibucá", cities: cities("La Esperanza") },
    { name: "Lempira", cities: cities("Gracias") },
    { name: "Ocotepeque", cities: cities("Nueva Ocotepeque") },
    { name: "Gracias a Dios", cities: cities("Puerto Lempira") },
    { name: "Islas de la Bahía", cities: cities("Roatán", "Coxen Hole") },
  ],
  SV: [
    { name: "San Salvador", cities: cities("San Salvador", "Soyapango", "Mejicanos", "Apopa") },
    { name: "Santa Ana", cities: cities("Santa Ana") },
    { name: "San Miguel", cities: cities("San Miguel") },
    { name: "La Libertad", cities: cities("Santa Tecla", "Antiguo Cuscatlán") },
    { name: "Sonsonate", cities: cities("Sonsonate") },
    { name: "Usulután", cities: cities("Usulután") },
    { name: "La Paz", cities: cities("Zacatecoluca") },
    { name: "Cuscatlán", cities: cities("Cojutepeque") },
    { name: "La Unión", cities: cities("La Unión") },
    { name: "Chalatenango", cities: cities("Chalatenango") },
    { name: "Cabañas", cities: cities("Sensuntepeque") },
    { name: "San Vicente", cities: cities("San Vicente") },
    { name: "Morazán", cities: cities("San Francisco Gotera") },
    { name: "Ahuachapán", cities: cities("Ahuachapán") },
  ],
  NI: [
    { name: "Managua", cities: cities("Managua", "Ciudad Sandino", "Tipitapa") },
    { name: "León", cities: cities("León") },
    { name: "Masaya", cities: cities("Masaya") },
    { name: "Chinandega", cities: cities("Chinandega") },
    { name: "Granada", cities: cities("Granada") },
    { name: "Estelí", cities: cities("Estelí") },
    { name: "Matagalpa", cities: cities("Matagalpa") },
    { name: "Jinotega", cities: cities("Jinotega") },
    { name: "Carazo", cities: cities("Jinotepe") },
    { name: "Rivas", cities: cities("Rivas") },
    { name: "Chontales", cities: cities("Juigalpa") },
    { name: "Boaco", cities: cities("Boaco") },
    { name: "Nueva Segovia", cities: cities("Ocotal") },
    { name: "Madriz", cities: cities("Somoto") },
    { name: "Río San Juan", cities: cities("San Carlos") },
    { name: "RACCS", cities: cities("Bluefields") },
    { name: "RACCN", cities: cities("Puerto Cabezas") },
  ],
  CR: [
    { name: "San José", cities: cities("San José", "Desamparados", "Curridabat", "Escazú", "Santa Ana") },
    { name: "Alajuela", cities: cities("Alajuela", "San Ramón", "Grecia") },
    { name: "Cartago", cities: cities("Cartago", "Paraíso", "Turrialba") },
    { name: "Heredia", cities: cities("Heredia", "San Pablo", "Belén") },
    { name: "Guanacaste", cities: cities("Liberia", "Nicoya", "Santa Cruz") },
    { name: "Puntarenas", cities: cities("Puntarenas", "Jacó", "Quepos") },
    { name: "Limón", cities: cities("Limón", "Guápiles") },
  ],
  PA: [
    { name: "Panamá", cities: cities("Panama City", "San Miguelito", "Tocumen") },
    { name: "Colón", cities: cities("Colón") },
    { name: "Chiriquí", cities: cities("David") },
    { name: "Coclé", cities: cities("Penonomé") },
    { name: "Herrera", cities: cities("Chitré") },
    { name: "Los Santos", cities: cities("Las Tablas") },
    { name: "Veraguas", cities: cities("Santiago") },
    { name: "Bocas del Toro", cities: cities("Bocas del Toro", "Changuinola") },
    { name: "Darién", cities: cities("La Palma") },
    { name: "Panamá Oeste", cities: cities("La Chorrera", "Arraiján", "Westland") },
  ],
  CO: [
    { name: "Bogotá D.C.", cities: cities("Bogotá") },
    { name: "Antioquia", cities: cities("Medellín", "Bello", "Envigado", "Itagüí") },
    { name: "Valle del Cauca", cities: cities("Cali", "Palmira", "Buenaventura") },
    { name: "Atlántico", cities: cities("Barranquilla", "Soledad") },
    { name: "Bolívar", cities: cities("Cartagena") },
    { name: "Santander", cities: cities("Bucaramanga", "Floridablanca") },
    { name: "Cundinamarca", cities: cities("Soacha", "Girardot") },
    { name: "Norte de Santander", cities: cities("Cúcuta") },
    { name: "Tolima", cities: cities("Ibagué") },
    { name: "Risaralda", cities: cities("Pereira") },
    { name: "Caldas", cities: cities("Manizales") },
    { name: "Quindío", cities: cities("Armenia") },
    { name: "Nariño", cities: cities("Pasto") },
    { name: "Huila", cities: cities("Neiva") },
    { name: "Meta", cities: cities("Villavicencio") },
    { name: "Magdalena", cities: cities("Santa Marta") },
    { name: "Cesar", cities: cities("Valledupar") },
    { name: "Córdoba", cities: cities("Montería") },
    { name: "Sucre", cities: cities("Sincelejo") },
    { name: "Boyacá", cities: cities("Tunja") },
    { name: "Cauca", cities: cities("Popayán") },
  ],
  BR: [
    { name: "São Paulo", cities: cities("São Paulo", "Campinas", "Guarulhos", "Santos", "São Bernardo do Campo") },
    { name: "Rio de Janeiro", cities: cities("Rio de Janeiro", "Niterói", "Duque de Caxias") },
    { name: "Distrito Federal", cities: cities("Brasília") },
    { name: "Minas Gerais", cities: cities("Belo Horizonte", "Uberlândia", "Contagem") },
    { name: "Bahia", cities: cities("Salvador", "Feira de Santana") },
    { name: "Paraná", cities: cities("Curitiba", "Londrina") },
    { name: "Rio Grande do Sul", cities: cities("Porto Alegre", "Caxias do Sul") },
    { name: "Pernambuco", cities: cities("Recife", "Olinda", "Jaboatão") },
    { name: "Ceará", cities: cities("Fortaleza") },
    { name: "Goiás", cities: cities("Goiânia") },
    { name: "Amazonas", cities: cities("Manaus") },
    { name: "Pará", cities: cities("Belém") },
    { name: "Santa Catarina", cities: cities("Florianópolis", "Joinville") },
    { name: "Espírito Santo", cities: cities("Vitória", "Vila Velha") },
    { name: "Maranhão", cities: cities("São Luís") },
    { name: "Paraíba", cities: cities("João Pessoa") },
    { name: "Rio Grande do Norte", cities: cities("Natal") },
    { name: "Alagoas", cities: cities("Maceió") },
    { name: "Sergipe", cities: cities("Aracaju") },
    { name: "Piauí", cities: cities("Teresina") },
    { name: "Mato Grosso", cities: cities("Cuiabá") },
    { name: "Mato Grosso do Sul", cities: cities("Campo Grande") },
  ],
  AR: [
    { name: "Ciudad Autónoma de Buenos Aires", cities: cities("CABA") },
    {
      name: "Buenos Aires",
      cities: cities("La Plata", "Mar del Plata", "Bahía Blanca", "Quilmes", "Lanús", "Lomas de Zamora"),
    },
    { name: "Córdoba", cities: cities("Córdoba") },
    { name: "Santa Fe", cities: cities("Rosario", "Santa Fe") },
    { name: "Mendoza", cities: cities("Mendoza") },
    { name: "Tucumán", cities: cities("San Miguel de Tucumán") },
    { name: "Salta", cities: cities("Salta") },
    { name: "Entre Ríos", cities: cities("Paraná") },
    { name: "Misiones", cities: cities("Posadas") },
    { name: "Chaco", cities: cities("Resistencia") },
    { name: "Corrientes", cities: cities("Corrientes") },
    { name: "Santiago del Estero", cities: cities("Santiago del Estero") },
    { name: "San Juan", cities: cities("San Juan") },
    { name: "Jujuy", cities: cities("San Salvador de Jujuy") },
    { name: "Río Negro", cities: cities("Viedma", "Bariloche") },
    { name: "Neuquén", cities: cities("Neuquén") },
    { name: "Formosa", cities: cities("Formosa") },
    { name: "Chubut", cities: cities("Rawson", "Comodoro Rivadavia") },
    { name: "San Luis", cities: cities("San Luis") },
    { name: "Catamarca", cities: cities("San Fernando del Valle de Catamarca") },
    { name: "La Rioja", cities: cities("La Rioja") },
    { name: "La Pampa", cities: cities("Santa Rosa") },
    { name: "Santa Cruz", cities: cities("Río Gallegos") },
    { name: "Tierra del Fuego", cities: cities("Ushuaia") },
  ],
  PE: [
    { name: "Lima", cities: cities("Lima", "Miraflores", "San Isidro", "Surco", "La Molina", "Callao") },
    { name: "Arequipa", cities: cities("Arequipa") },
    { name: "La Libertad", cities: cities("Trujillo") },
    { name: "Cusco", cities: cities("Cusco") },
    { name: "Piura", cities: cities("Piura") },
    { name: "Lambayeque", cities: cities("Chiclayo") },
    { name: "Junín", cities: cities("Huancayo") },
    { name: "Ica", cities: cities("Ica") },
    { name: "Ancash", cities: cities("Huaraz", "Chimbote") },
    { name: "Puno", cities: cities("Puno", "Juliaca") },
    { name: "Loreto", cities: cities("Iquitos") },
    { name: "Cajamarca", cities: cities("Cajamarca") },
    { name: "Ucayali", cities: cities("Pucallpa") },
    { name: "San Martín", cities: cities("Tarapoto") },
    { name: "Tacna", cities: cities("Tacna") },
    { name: "Ayacucho", cities: cities("Ayacucho") },
    { name: "Huánuco", cities: cities("Huánuco") },
    { name: "Moquegua", cities: cities("Moquegua") },
  ],
  CL: [
    { name: "Región Metropolitana", cities: cities("Santiago", "Puente Alto", "Maipú", "La Florida", "Las Condes", "Providencia") },
    { name: "Valparaíso", cities: cities("Valparaíso", "Viña del Mar", "Quilpué") },
    { name: "Biobío", cities: cities("Concepción", "Talcahuano", "Los Ángeles") },
    { name: "Araucanía", cities: cities("Temuco") },
    { name: "Los Lagos", cities: cities("Puerto Montt", "Osorno") },
    { name: "Maule", cities: cities("Talca", "Curicó") },
    { name: "Coquimbo", cities: cities("La Serena", "Coquimbo") },
    { name: "Antofagasta", cities: cities("Antofagasta", "Calama") },
    { name: "O'Higgins", cities: cities("Rancagua") },
    { name: "Tarapacá", cities: cities("Iquique") },
    { name: "Los Ríos", cities: cities("Valdivia") },
    { name: "Ñuble", cities: cities("Chillán") },
    { name: "Arica y Parinacota", cities: cities("Arica") },
    { name: "Atacama", cities: cities("Copiapó") },
    { name: "Magallanes", cities: cities("Punta Arenas") },
  ],
  EC: [
    { name: "Pichincha", cities: cities("Quito", "Sangolquí") },
    { name: "Guayas", cities: cities("Guayaquil", "Durán", "Samborondón") },
    { name: "Azuay", cities: cities("Cuenca") },
    { name: "Manabí", cities: cities("Manta", "Portoviejo") },
    { name: "Tungurahua", cities: cities("Ambato") },
    { name: "El Oro", cities: cities("Machala") },
    { name: "Imbabura", cities: cities("Ibarra") },
    { name: "Loja", cities: cities("Loja") },
    { name: "Los Ríos", cities: cities("Babahoyo", "Quevedo") },
    { name: "Chimborazo", cities: cities("Riobamba") },
    { name: "Santo Domingo", cities: cities("Santo Domingo") },
    { name: "Esmeraldas", cities: cities("Esmeraldas") },
    { name: "Santa Elena", cities: cities("Santa Elena", "Salinas") },
    { name: "Cotopaxi", cities: cities("Latacunga") },
    { name: "Sucumbíos", cities: cities("Nueva Loja") },
  ],
  BO: [
    { name: "La Paz", cities: cities("La Paz", "El Alto") },
    { name: "Santa Cruz", cities: cities("Santa Cruz de la Sierra") },
    { name: "Cochabamba", cities: cities("Cochabamba") },
    { name: "Oruro", cities: cities("Oruro") },
    { name: "Potosí", cities: cities("Potosí") },
    { name: "Chuquisaca", cities: cities("Sucre") },
    { name: "Tarija", cities: cities("Tarija") },
    { name: "Beni", cities: cities("Trinidad") },
    { name: "Pando", cities: cities("Cobija") },
  ],
  DO: [
    { name: "Distrito Nacional", cities: cities("Santo Domingo") },
    { name: "Santo Domingo", cities: cities("Santo Domingo Este", "Santo Domingo Norte", "Santo Domingo Oeste") },
    { name: "Santiago", cities: cities("Santiago de los Caballeros") },
    { name: "La Romana", cities: cities("La Romana") },
    { name: "San Cristóbal", cities: cities("San Cristóbal") },
    { name: "La Altagracia", cities: cities("Punta Cana", "Higüey") },
    { name: "Puerto Plata", cities: cities("Puerto Plata") },
    { name: "Duarte", cities: cities("San Francisco de Macorís") },
    { name: "San Pedro de Macorís", cities: cities("San Pedro de Macorís") },
    { name: "La Vega", cities: cities("La Vega") },
    { name: "Espaillat", cities: cities("Moca") },
    { name: "Barahona", cities: cities("Barahona") },
    { name: "Azua", cities: cities("Azua") },
    { name: "Peravia", cities: cities("Baní") },
    { name: "Monseñor Nouel", cities: cities("Bonao") },
  ],
  PR: [
    { name: "San Juan", cities: cities("San Juan", "Santurce", "Río Piedras", "Condado") },
    { name: "Bayamón", cities: cities("Bayamón") },
    { name: "Carolina", cities: cities("Carolina") },
    { name: "Ponce", cities: cities("Ponce") },
    { name: "Caguas", cities: cities("Caguas") },
    { name: "Guaynabo", cities: cities("Guaynabo") },
    { name: "Mayagüez", cities: cities("Mayagüez") },
    { name: "Arecibo", cities: cities("Arecibo") },
    { name: "Toa Baja", cities: cities("Toa Baja") },
    { name: "Toa Alta", cities: cities("Toa Alta") },
    { name: "Trujillo Alto", cities: cities("Trujillo Alto") },
  ],
};

export function getCheckoutDivisions(country: CountryCode): GeoDivision[] {
  return CHECKOUT_GEO[country] ?? [];
}

export function getCitiesForState(country: CountryCode, state: string): string[] {
  const divisions = getCheckoutDivisions(country);
  if (!state) {
    return divisions.flatMap((d) => d.cities);
  }
  const match = divisions.find((d) => d.name === state);
  return match?.cities ?? [];
}

export function isSingleDivisionCountry(country: CountryCode): boolean {
  const divisions = getCheckoutDivisions(country);
  return divisions.length <= 1;
}
