/** Ecuador — Provincia → Ciudad/Parroquia (complete official list). */
export type EcuadorGeoTree = Record<string, string[]>;

export const GEO_EC: EcuadorGeoTree = {
  "Azuay": [
    "Abdón Calderón",
    "Amaluza",
    "Baños",
    "Bulán",
    "Camilo Ponce enríquez",
    "Chaucha",
    "Checa",
    "Chicán",
    "Chiquintad",
    "Chordeleg",
    "Chumblín",
    "Cochapata",
    "Cuchil",
    "Cuenca",
    "Cumbe",
    "Daniel Córdova Toral",
    "Dug Dug",
    "El Cabo",
    "El Carmen de Pijilí",
    "El Pan",
    "El Progreso",
    "Girón",
    "Guachapala",
    "Gualaceo",
    "Guarainag",
    "Güel",
    "Jadán",
    "Jima",
    "La Asunción",
    "La Unión",
    "Las Nieves",
    "Llacao",
    "Ludo",
    "Luis Cordero Vega",
    "Luis Galarza Orellana",
    "Mariano Moreno",
    "Molleturo",
    "Nabón",
    "Nulti",
    "Octavio Cordero Palacios",
    "Oña",
    "Paccha",
    "Palmas",
    "Paute",
    "Principal",
    "Pucará",
    "Quingeo",
    "Remigio Crespo Toral",
    "Ricaurte",
    "San Bartolomé",
    "San Cristóbal",
    "San Felipe de Oña",
    "San Fernando",
    "San Gerardo",
    "San Joaquín",
    "San José de Raranga",
    "San Juan",
    "San Martín de Puzhio",
    "San Rafael de Sharug",
    "San Salvador de Cañaribamba",
    "San Vicente",
    "Santa Ana",
    "Santa Isabel",
    "Sayausí",
    "Sevilla de Oro",
    "Shaglli",
    "Sidcay",
    "Sígsig",
    "Simón Bolívar",
    "Sinincay",
    "Susudel",
    "Tarqui",
    "Tomebamba",
    "Turi",
    "Valle",
    "Victoria del Portete",
    "Zhidmad"
  ],
  "Bolívar": [
    "Asunción",
    "Balsapamba",
    "Bilován",
    "Caluma",
    "Chillanes",
    "Chimbo",
    "Echeandía",
    "Facundo Vela",
    "Guaranda",
    "Julio E. Moreno",
    "La Magdalena",
    "Las Naves",
    "Régulo de Mora",
    "Salinas",
    "San José de Chimbo",
    "San José del Tambo",
    "San Lorenzo",
    "San Luis de Pambil",
    "San Miguel",
    "San Pablo",
    "San Sebastián",
    "San Simón",
    "San Vicente",
    "Santa Fe",
    "Santiago",
    "Simiátug",
    "Telimbela"
  ],
  "Cañar": [
    "Azogues",
    "Biblián",
    "Cañar",
    "Chontamarca",
    "Chorocopte",
    "Cojitambo",
    "Déleg",
    "Ducur",
    "El Tambo",
    "General Morales",
    "Gualleturo",
    "Guapán",
    "Honorato Vásquez",
    "Ingapirca",
    "Javier Loyola",
    "Jerusalén",
    "Juncal",
    "La Troncal",
    "Luis Cordero",
    "Manuel J. Calle",
    "Nazón",
    "Pancho Negro",
    "Pindilig",
    "Rivera",
    "San Antonio",
    "San Francisco de Sageo",
    "San Miguel",
    "Solano",
    "Suscal",
    "Taday",
    "Turupamba",
    "Ventura",
    "Zhud"
  ],
  "Carchi": [
    "Bolívar",
    "Chitán de Navarrete",
    "Concepción",
    "Cristóbal Colón",
    "El Ángel",
    "El Carmelo",
    "El Chical",
    "El Goaltal",
    "Espejo",
    "Fernández Salvador",
    "García Moreno",
    "Huaca",
    "Jijón y Caamaño",
    "Juan Montalvo",
    "Julio Andrade",
    "La Libertad",
    "La Paz",
    "Los Andes",
    "Maldonado",
    "Mariscal Sucre",
    "Mira",
    "Monte Olivo",
    "Montúfar",
    "Piartal",
    "Pioter",
    "San Gabriel",
    "San Isidro",
    "San Pedro de Huaca",
    "San Rafael",
    "San Vicente de Pusir",
    "Santa Martha de Cuba",
    "Tobar Donoso",
    "Tufiño",
    "Tulcán",
    "Urbina"
  ],
  "Cotopaxi": [
    "Aláquez",
    "Angamarca",
    "Antonio José Holguín",
    "Belisario Quevedo",
    "Canchagua",
    "Chantilín",
    "Chugchillán",
    "Cochapamba",
    "Cusubamba",
    "El Corazón",
    "Guangaje",
    "Guasaganda",
    "Guaytacama",
    "Isinlivi",
    "Joseguango Bajo",
    "La Maná",
    "La Victoria",
    "Las Pampas",
    "Latacunga",
    "Moraspungo",
    "Mulalillo",
    "Mulaló",
    "Mulliquindil",
    "Once de Noviembre",
    "Palo Quemado",
    "Pangua",
    "Pansaleo",
    "Pilaló",
    "Pinllopata",
    "Poaló",
    "Pucayacu",
    "Pujilí",
    "Ramón Campaña",
    "Salcedo",
    "San Juan de Pastocalle",
    "San Miguel",
    "Saquisilí",
    "Sigchos",
    "Tanicuchi",
    "Tingo",
    "Toacaso",
    "Zumbahua"
  ],
  "Chimborazo": [
    "Achupallas",
    "Alausí",
    "Bilbao",
    "Cacha",
    "Calpi",
    "Cañi",
    "Capzol",
    "Cebadas",
    "Chambo",
    "Chunchi",
    "Colta",
    "Columbe",
    "Compud",
    "Cubijíes",
    "Cumandá",
    "El Altar",
    "Flores",
    "Gonzol",
    "Guamote",
    "Guanando",
    "Guano",
    "Guasuntos",
    "Huigra",
    "Ilapo",
    "Juan de Velasco",
    "La Candelaria",
    "La Providencia",
    "Licán",
    "Licto",
    "Llagos",
    "Matus",
    "Multitud",
    "Pallatanga",
    "Palmira",
    "Penipe",
    "Pistishi",
    "Puela",
    "Pumallacta",
    "Pungalá",
    "Punín",
    "Quimiag",
    "Riobamba",
    "San Andrés",
    "San Antonio de Bayushig",
    "San Gerardo",
    "San Isidro de Patulú",
    "San José del Chazo",
    "San Juan",
    "San Luis",
    "Santa Fé de Galán",
    "Santiago de Quito",
    "Sevilla",
    "Sibambe",
    "Tixán",
    "Valparaiso",
    "Villa la Unión"
  ],
  "El Oro": [
    "Abañín",
    "Arcapamba",
    "Arenillas",
    "Atahualpa",
    "Ayapamba",
    "Balsas",
    "Barbones",
    "Bellamaría",
    "Bellavista",
    "Buenavista",
    "Cañaquemada",
    "Capiro",
    "Carcabón",
    "Casacay",
    "Chacras",
    "Chilla",
    "Cordoncillo",
    "Curtincapa",
    "El Guabo",
    "El Ingenio",
    "El Paraíso",
    "El Retiro",
    "Guanazán",
    "Guizhaguiña",
    "Huaquillas",
    "Huertas",
    "Jambelí",
    "La Avanzada",
    "La Bocana",
    "La Cuca",
    "La Iberia",
    "La Libertad",
    "La Peaña",
    "La Victoria",
    "Las Lajas",
    "Machala",
    "Malvas",
    "Marcabelí",
    "Milagro",
    "Morales",
    "Moromoro",
    "Muluncay Grande",
    "Paccha",
    "Palmales",
    "Pasaje",
    "Piedras",
    "Piñas",
    "Portovelo",
    "Progreso",
    "Río Bonito",
    "Salatí",
    "Salvias",
    "San Antonio",
    "San Isidro",
    "San José",
    "San Juan de Cerro Azul",
    "San Roque",
    "Santa Rosa",
    "Saracay",
    "Sinsao",
    "Tendales",
    "Torata",
    "Uzhcurrumi",
    "Victoria",
    "Zaruma"
  ],
  "Esmeraldas": [
    "5 de Junio",
    "Alto Tambo",
    "Anchayacu",
    "Ancón",
    "Atacames",
    "Atahualpa",
    "Bolívar",
    "Borbón",
    "Calderón",
    "Camarones",
    "Carondelet",
    "Chinca",
    "Chontaduro",
    "Chumundé",
    "Chura",
    "Colón Eloy del María",
    "Concepción",
    "Coronel Carlos Concha Torres",
    "Cube",
    "Daule",
    "Eloy Alfaro",
    "Esmeraldas",
    "Galera",
    "La Tola",
    "La Unión",
    "Lagarto",
    "Luis Vargas Torres",
    "Majua",
    "Maldonado",
    "Malimpia",
    "Mataje",
    "Montalvo",
    "Muisne",
    "Pampanal de Bolívar",
    "Quingue",
    "Quinindé",
    "Rioverde",
    "Rocafuerte",
    "Rosa Zárate",
    "Sálima",
    "San Francisco",
    "San Francisco de Onzole",
    "San Gregorio",
    "San Javier de Cachaví",
    "San José de Cayapas",
    "San José de Chamanga",
    "San Lorenzo",
    "San Mateo",
    "Santa Lucía de Las Peñas",
    "Santa Rita",
    "Santo Domingo de Onzole",
    "Selva Alegre",
    "Súa",
    "Tabiazo",
    "Tachina",
    "Tambillo",
    "Telembí",
    "Timbiré",
    "Tonchigüe",
    "Tonsupa",
    "Tululbí",
    "Urbina",
    "Valdez",
    "Viche",
    "Vuelta Larga"
  ],
  "Guayas": [
    "Alfredo Baquerizo Moreno (Juján)",
    "Balao",
    "Balzar",
    "Chobo",
    "Colimes",
    "Coronel Lorenzo de Garaycoa",
    "Coronel Marcelino Maridueña",
    "Daule",
    "Durán",
    "El Empalme",
    "El Rosario",
    "El Salitre",
    "El Triunfo",
    "Eloy Alfaro",
    "General  Antonio Elizalde",
    "General Antonio Elizalde",
    "General Pedro J. Montero",
    "General Vernaza",
    "General Villamil",
    "Guayaquil",
    "Guayas",
    "Isidro Ayora",
    "Jesús María",
    "Juan Bautista Aguirre",
    "Juan Gómez Rendón",
    "Junquillal",
    "La Victoria",
    "Laurel",
    "Limonal",
    "Lomas de Sargentillo",
    "Los Lojas",
    "Mariscal Sucre",
    "Milagro",
    "Morro",
    "Naranjal",
    "Naranjito",
    "Narcisa de Jesús",
    "Nobol",
    "Palestina",
    "Pedro Carbo",
    "Playas",
    "Posorja",
    "Puná",
    "Roberto Astudillo",
    "Sabanilla",
    "Salitre",
    "Samborondón",
    "San Carlos",
    "San Jacinto",
    "San Jacinto de Yaguachi",
    "Santa Lucía",
    "Santa Rosa de Flandes",
    "Simón Bolívar",
    "Tarifa",
    "Taura",
    "Tenguel",
    "Valle de la Virgen",
    "Velasco Ibarra",
    "Virgen de Fátima",
    "Yaguachi Viejo"
  ],
  "Imbabura": [
    "Ambuquí",
    "Angochagua",
    "Antonio Ante",
    "Apuela",
    "Atuntaqui",
    "Cahuasquí",
    "Chugá",
    "Cotacachi",
    "Dr. Miguel Egas Cabezas",
    "Eugenio Espejo",
    "García Moreno",
    "González Suárez",
    "Ibarra",
    "Imantag",
    "Imbaya",
    "La Carolina",
    "La Esperanza",
    "La Merced de Buenos Aires",
    "Lita",
    "Mariano Acosta",
    "Otavalo",
    "Pablo Arenas",
    "Pataquí",
    "Peñaherrera",
    "Pimampiro",
    "Plaza Gutiérrez",
    "Quiroga",
    "Salinas",
    "San Antonio",
    "San Blas",
    "San Francisco de Natabuela",
    "San Francisco de Sigsipamba",
    "San José de Chaltura",
    "San José de Quichinche",
    "San Juan de Ilumán",
    "San Miguel de Ibarra",
    "San Miguel de Urcuquí",
    "San Pablo",
    "San Rafael",
    "San Roque",
    "Seis de Julio de Cuellaje",
    "Selva Alegre",
    "Tumbabiro",
    "Urcuquí",
    "Vacas Galindo"
  ],
  "Loja": [
    "12 de Diciembre",
    "27 de Abril",
    "Alamor",
    "Amaluza",
    "Amarillos",
    "Bellavista",
    "Bolaspamba",
    "Buenavista",
    "Calvas",
    "Cangonamá",
    "Cariamanga",
    "Casanga",
    "Catacocha",
    "Catamayo",
    "Cazaderos",
    "Celica",
    "Chaguarpamba",
    "Changaimina",
    "Chantaco",
    "Chaquinal",
    "Chuquiribamba",
    "Ciano",
    "Colaisaca",
    "Cruzpamba",
    "El Airo",
    "El Arenal",
    "El Cisne",
    "El Ingenio",
    "El Limo",
    "El Lucero",
    "El Paraíso de Celen",
    "El Rosario",
    "El Tablón",
    "El Tambo",
    "Espíndola",
    "Fundochamba",
    "Garzareal",
    "Gonzanamá",
    "Guachanamá",
    "Gualel",
    "Guayquichuma",
    "Jimbilla",
    "Jimbura",
    "La Tingue",
    "La Victoria",
    "Larama",
    "Lauro Guerrero",
    "Limones",
    "Lluzhapa",
    "Loja",
    "Macará",
    "Malacatos",
    "Mangahurco",
    "Manú",
    "Mercadillo",
    "Milagros",
    "Nambacola",
    "Nueva Fátima",
    "Olmedo",
    "Orianga",
    "Paletillas",
    "Paltas",
    "Pindal",
    "Pózul",
    "Purunuma",
    "Puyango",
    "Quilanga",
    "Quinara",
    "Sabanilla",
    "Sabiango",
    "Sacapalca",
    "San Antonio",
    "San Antonio de Las Aradas",
    "San Antonio de Qumbe",
    "San Lucas",
    "San Pablo de Tenta",
    "San Pedro de la Bendita",
    "San Pedro de Vilcabamba",
    "San Sebastián de Yúluc",
    "Sanguillín",
    "Santa Rufina",
    "Santa Teresita",
    "Santiago",
    "Saraguro",
    "Selva Alegre",
    "Sozoranga",
    "Sumaypamba",
    "Tacamoros",
    "Taquil",
    "Teniente Maximiliano Rodríguez Loaiza",
    "Urdaneta",
    "Utuana",
    "Vicentino",
    "Vilcabamba",
    "Yamana",
    "Yangana",
    "Zambi",
    "Zapotillo"
  ],
  "Los Ríos": [
    "Antonio Sotomayor",
    "Baba",
    "Babahoyo",
    "Buena Fe",
    "Caracol",
    "Catarama",
    "Chacarita",
    "Febres Cordero",
    "Guare",
    "Isla de Bejucal",
    "La Esmeralda",
    "La Esperanza",
    "La Unión",
    "Los Ángeles",
    "Mocache",
    "Montalvo",
    "Palenque",
    "Patricia Pilar",
    "Pimocha",
    "Puebloviejo",
    "Puerto Pechiche",
    "Quevedo",
    "Quinsaloma",
    "Ricaurte",
    "San Carlos",
    "San Jacinto de Buena Fe",
    "San Juan",
    "Urdaneta",
    "Valencia",
    "Ventanas",
    "Vinces",
    "Zapotal"
  ],
  "Manabí": [
    "24 de Mayo",
    "Abdón Calderón",
    "Alhajuela",
    "América",
    "Ángel Pedro Giler",
    "Arquitecto Sixto Durán Ballén",
    "Atahualpa",
    "Ayacucho",
    "Bachillero",
    "Bahia de Caráquez",
    "Barraganete",
    "Bellavista",
    "Bolívar",
    "Boyacá",
    "Calceta",
    "Campozano",
    "Canoa",
    "Canuto",
    "Cascol",
    "Charapotó",
    "Chibunga",
    "Chirijos",
    "Chone",
    "Cojimíes",
    "Convento",
    "Crucita",
    "Diez de Agosto",
    "El Anegado",
    "El Carmen",
    "El Paraíso la 14",
    "Eloy Alfaro",
    "Flavio Alfaro",
    "Guale",
    "Honorato Vásquez",
    "Jama",
    "Jaramijó",
    "Jipijapa",
    "Julcuy",
    "Junín",
    "La Pila",
    "La Unión",
    "Lascano",
    "Machalilla",
    "Manta",
    "Membrillal",
    "Membrillo",
    "Montecristi",
    "Noboa",
    "Olmedo",
    "Paján",
    "Pedernales",
    "Pedro Pablo Gómez",
    "Pichincha",
    "Portoviejo",
    "Pueblo Nuevo",
    "Puerto Cayo",
    "Puerto López",
    "Quiroga",
    "Ricaurte",
    "Riochico",
    "Rocafuerte",
    "Salango",
    "San Antonio",
    "San Francisco de Novillo",
    "San Isidro",
    "San Lorenzo",
    "San Pablo",
    "San Pedro de Suma",
    "San Plácido",
    "San Sebastián",
    "San Vicente",
    "Santa Ana",
    "Santa Ana de Vuelta Larga",
    "Santa María",
    "Santa Marianita",
    "Sucre",
    "Tosagua",
    "Wilfrido Loor Moreira",
    "Zapallo"
  ],
  "Morona Santiago": [
    "16 de Agosto",
    "Alshi",
    "Amazonas",
    "Arapicos",
    "Asunción",
    "Bermejos",
    "Bomboíza",
    "Chiguaza",
    "Chigüinda",
    "Chupianza",
    "Copal",
    "Cuchaentza",
    "Cumandá",
    "El Ideal",
    "El Rosario",
    "General Proaño",
    "Gral. Leonidas Plaza Gutiérrez",
    "Gualaquiza",
    "Huambi",
    "Huamboya",
    "Huasaga",
    "Indanza",
    "Limón Indanza",
    "Logroño",
    "Macas",
    "Macuma",
    "Morona",
    "Nueva Tarqui",
    "Pablo Sexto",
    "Palora",
    "Pan de Azúcar",
    "Patuca",
    "Pumpuentsa",
    "Río Blanco",
    "San Antonio",
    "San Carlos de Limón",
    "San Francisco de Chinimbimi",
    "San Isidro",
    "San Jacinto de Wakambeis",
    "San José de Morona",
    "San Juan Bosco",
    "San Luis de El Acho",
    "San Miguel de Conchay",
    "San Miguel de Cuyes",
    "Sangay",
    "Santa Marianita de Jesús",
    "Santa Susana de Chiviaza",
    "Santiago",
    "Santiago de Méndez",
    "Santiago de Pananza",
    "Sevilla Don Bosco",
    "Shimpis",
    "Sinaí",
    "Sucúa",
    "Taisha",
    "Tayuza",
    "Tiwintza",
    "Tuutinentsa",
    "Yaupi",
    "Yunganza",
    "Zuña"
  ],
  "Napo": [
    "Ahuano",
    "Archidona",
    "Baeza",
    "Carlos Julio Arosemena Tola",
    "Chontapunta",
    "Cosanga",
    "Cotundo",
    "Cuyuja",
    "El Chaco",
    "Gonzalo Díaz de Pineda",
    "Hatun Sumaku",
    "Linares",
    "Oyacachi",
    "Pano",
    "Papallacta",
    "Puerto Misahuallí",
    "Puerto Napo",
    "Quijos",
    "San Francisco de Borja",
    "San Juan de Muyuna",
    "San Pablo de Ushpayacu",
    "Santa Rosa",
    "Sardinas",
    "Sumaco",
    "Tálag",
    "Tena"
  ],
  "Pastaza": [
    "Arajuno",
    "Canelos",
    "Curaray",
    "Diez de Agosto",
    "El Triunfo",
    "Fátima",
    "Madre Tierra",
    "Mera",
    "Montalvo",
    "Pastaza",
    "Pomona",
    "Puyo",
    "Río Corrientes",
    "Río Tigre",
    "San José",
    "Santa Clara",
    "Sarayacu",
    "Shell",
    "Simón Bolívar",
    "Tarqui",
    "Teniente Hugo Ortiz",
    "Veracruz"
  ],
  "Pichincha": [
    "Alangasí",
    "Aloag",
    "Aloasí",
    "Amaguaña",
    "Ascázubi",
    "Atahualpa",
    "Calacalí",
    "Calderón",
    "Cangahua",
    "Cayambe",
    "Chavezpamba",
    "Checa",
    "Conocoto",
    "Cotogchoa",
    "Cumbayá",
    "Cutuglahua",
    "Distrito Metropolitano de Quito",
    "El Chaupi",
    "El Quinche",
    "Gualea",
    "Guangopolo",
    "Guayllabamba",
    "La Esperanza",
    "La Merced",
    "Llano Chico",
    "Lloa",
    "Machachi",
    "Malchinguí",
    "Manuel Cornejo Astorga",
    "Mejía",
    "Mindo",
    "Nanegal",
    "Nanegalito",
    "Nayón",
    "Nono",
    "Olmedo",
    "Otón",
    "Pacto",
    "Pedro Moncayo",
    "Pedro Vicente Maldonado",
    "Perucho",
    "Pifo",
    "Píntag",
    "Pomasqui",
    "Puéllaro",
    "Puembo",
    "Puerto Quito",
    "Quito",
    "Rumiñahui",
    "Rumipamba",
    "San Antonio",
    "San José de Ayora",
    "San José de Minas",
    "San Miguel de los Bancos",
    "Sangolquí",
    "Santa Rosa de Cuzubamba",
    "Tababela",
    "Tabacundo",
    "Tambillo",
    "Tocachi",
    "Tumbaco",
    "Tupigachi",
    "Uyumbicho",
    "Yaruquí",
    "Zámbiza"
  ],
  "Tungurahua": [
    "Ambatillo",
    "Ambato",
    "Atahualpa",
    "Augusto N. Martínez",
    "Baños",
    "Baños de Agua Santa",
    "Baquerizo Moreno",
    "Benítez",
    "Bolívar",
    "Cevallos",
    "Chiquicha",
    "Constantino Fernández",
    "Cotaló",
    "Cunchibamba",
    "El Rosario",
    "El Triunfo",
    "Emilio María Terán",
    "García Moreno",
    "Guambaló",
    "Huachi Grande",
    "Izamba",
    "Juan Benigno Vela",
    "Lligua",
    "Los Andes",
    "Marcos Espinel",
    "Mocha",
    "Montalvo",
    "Pasa",
    "Patate",
    "Pelileo",
    "Picaihua",
    "Pilagüín",
    "Píllaro",
    "Pinguilí",
    "Presidente Urbina",
    "Quero",
    "Quinchicoto",
    "Quisapincha",
    "Río Negro",
    "Río Verde",
    "Rumipamba",
    "Salasaca",
    "San Andrés",
    "San Bartolomé de Pinllo",
    "San Fernando",
    "San José de Poaló",
    "San Miguelito",
    "San Pedro de Pelileo",
    "Santa Rosa",
    "Santiago de Píllaro",
    "Sucre",
    "Tisaleo",
    "Totoras",
    "Ulba",
    "Unamuncho",
    "Yanayacu Mochapata"
  ],
  "Zamora Chinchipe": [
    "28 de Mayo",
    "Bellavista",
    "Centinela del Cóndor",
    "Chicaña",
    "Chinchipe",
    "Chito",
    "Cumbaratza",
    "El Chorro",
    "El Guisme",
    "El Pangui",
    "El Porvenir del Carmen",
    "Guadalupe",
    "Guayzimi",
    "Imbana",
    "La Canela",
    "La Chonta",
    "La Paz",
    "Los encuentros",
    "Nangaritza",
    "Nankais",
    "Nuevo Paraíso",
    "Nuevo Quito",
    "Pachicutza",
    "Palanda",
    "Panguintza",
    "Paquisha",
    "Pucapamba",
    "Sabanilla",
    "San Andrés",
    "San Carlos de Las Minas",
    "San Francisco del Vergel",
    "Timbara",
    "Triunfo Dorado",
    "Tundayme",
    "Tutupali",
    "Valladolid",
    "Yacuambi",
    "Yantzaza",
    "Zamora",
    "Zumba",
    "Zumbi",
    "Zurmi"
  ],
  "Galápagos": [
    "Bella Vista",
    "El Progreso",
    "Isabela",
    "Isla Santa María Floreana",
    "Puerto Ayora",
    "Puerto Baquerizo Moreno",
    "Puerto Villamil",
    "San Cristóbal",
    "Santa Cruz",
    "Santa Rosa",
    "Tomás de Berlanga"
  ],
  "Sucumbíos": [
    "10 de Agosto",
    "Aguas Negras",
    "Cascales",
    "Cuyabeno",
    "Dureno",
    "El Dorado de Cascales",
    "El eno",
    "El Playón de San Francisco",
    "El Reventador",
    "General Farfán",
    "Gonzalo Pizarro",
    "Jambelí",
    "La Bonita",
    "La Sofía",
    "Lago Agrio",
    "Limoncocha",
    "Lumbaquí",
    "Nueva Loja",
    "Nueva Troncal",
    "Pacayacu",
    "Palma Roja",
    "Pañacocha",
    "Puerto Bolívar",
    "Puerto El Carmen de Putumayo",
    "Puerto Libre",
    "Puerto Rodríguez",
    "Putumayo",
    "Rosa Florida",
    "San Pedro de los Cofánes",
    "San Roque",
    "Sansahuari",
    "Santa Bárbara",
    "Santa Cecilia",
    "Santa Elena",
    "Santa Rosa de Sucumbíos",
    "Sevilla",
    "Shushufindi",
    "Siete de Julio",
    "Sucumbíos",
    "Tarapoa"
  ],
  "Orellana": [
    "Aguarico",
    "Alejandro Labaka",
    "Ávila",
    "Capitán Augusto Rivadeneyra",
    "Cononaco",
    "Dayuma",
    "El Coca",
    "El Dorado",
    "El Edén",
    "enokanqui",
    "Francisco de Orellana",
    "García Moreno",
    "Inés Arango",
    "La Belleza",
    "La Joya de los Sachas",
    "Lago San Pedro",
    "Loreto",
    "Nuevo Paraíso",
    "Nuevo Rocafuerte",
    "Pompeya",
    "Puerto Murialdo",
    "Rumipamba",
    "San Carlos",
    "San José de Dahuano",
    "San José de Guayusa",
    "San José de Payamino",
    "San Luis de Armenia",
    "San Sebastián del Coca",
    "San Vicente de Huaticocha",
    "Santa María de Huiririma",
    "Taracoa",
    "Tres de Noviembre",
    "Unión Milagreña",
    "Yasuní"
  ],
  "Santo Domingo de los Tsáchilas": [
    "Alluriquín",
    "El Esfuerzo",
    "La Concordia",
    "La Villegas",
    "Luz de América",
    "Monterrey",
    "Plan Piloto",
    "Puerto Limón",
    "San Jacinto del Búa",
    "Santa María del Toachi",
    "Santo Domingo",
    "Santo Domingo de los Colorados",
    "Valle Hermoso"
  ],
  "Santa Elena": [
    "Anconcito",
    "Atahualpa",
    "Chanduy",
    "Colonche",
    "José Luis Tamayo",
    "La Libertad",
    "Manglaralto",
    "Salinas",
    "San José de Ancón",
    "Santa Elena",
    "Simón Bolívar"
  ]
};

export function usesEcuadorCodCheckout(country: string): boolean {
  return country.toUpperCase() === "EC";
}

export function ecuadorProvincias(): string[] {
  return Object.keys(GEO_EC).sort((a, b) => a.localeCompare(b, "es"));
}

export function ecuadorCiudades(provincia: string): string[] {
  return GEO_EC[provincia] ?? [];
}
