/** Ecuador — Provincia → Cantón from Fufills COD coverage. */
export type EcuadorGeoTree = Record<string, string[]>;
export const GEO_EC: EcuadorGeoTree = {
  "Azuay": [
    "Camilo Ponce Enríquez",
    "Chordeleg",
    "Cuenca",
    "El Pan",
    "Girón",
    "Guachapala",
    "Gualaceo",
    "Nabón",
    "Oña",
    "Paccha",
    "Paute",
    "Pucará",
    "Ricaurte",
    "San Fernando",
    "San Joaquin",
    "Santa Isabel",
    "Sayuasí",
    "Sevilla de Oro",
    "Sidcay",
    "Sigsig"
  ],
  "Bolívar": [
    "Asunción",
    "Caluma",
    "Chillanes",
    "Chimbo",
    "Echeandía",
    "Guaranda",
    "La Magdalena",
    "Las Naves",
    "Primero De Mayo",
    "San Jose De Chimbo",
    "San Lorenzo",
    "San Miguel",
    "San Pedro De Guanujo",
    "San Sebastián",
    "San Simón",
    "Santa Fé"
  ],
  "Carchi": [
    "Bolivar",
    "Espejo",
    "Mira",
    "Montufar",
    "San Gabriel",
    "San Pedro de Huaca",
    "Tulcán"
  ],
  "Cañar": [
    "Azogues",
    "Biblián",
    "Cañar",
    "Cojitambo",
    "Delég",
    "El Tambo",
    "Guapán",
    "Javier Loyola",
    "La Troncal",
    "Luis Cordero",
    "Manuel J Calle",
    "San Miguel",
    "Suscal"
  ],
  "Chimborazo": [
    "Alausí",
    "Chambo",
    "Chunchi",
    "Colta",
    "Cumandá",
    "Flores",
    "Guamote",
    "Guano",
    "Ilapo",
    "Lican",
    "Licto",
    "Pallatanga",
    "Penipe",
    "Punin",
    "Riobamba",
    "San Andrés",
    "San Juan",
    "San Luis",
    "Yaruquies"
  ],
  "Cotopaxi": [
    "Alaques",
    "Belisario Quevedo",
    "Guaytacama",
    "La Maná",
    "Lasso",
    "Latacunga",
    "Mulalo",
    "Mulliquindil",
    "Once de noviembre",
    "Pangua",
    "Panzaleo",
    "Pastocalle",
    "Poalo",
    "Pujilí",
    "Salcedo",
    "Saquisilí",
    "Sigchos",
    "Tanicuchi",
    "Toacaso"
  ],
  "El Oro": [
    "Arenillas",
    "Atahualpa",
    "Balsas",
    "Barbones",
    "Bellavista",
    "Buena Vista",
    "Cana Quemada",
    "Chillas",
    "El Cambio",
    "El Guabo",
    "El retiro",
    "Huaquillas",
    "La Avanzada",
    "La Iberia",
    "La Peaña",
    "Las Lajas",
    "Machala",
    "Marcabelí",
    "Pasaje",
    "Piñas",
    "Portovelo",
    "Puerto Bolivar",
    "Santa Rosa",
    "Torata",
    "Veitoria",
    "Zaruma"
  ],
  "Esmeraldas": [
    "Atacames",
    "Colimes",
    "Eloy Alfaro",
    "Esmeraldas",
    "La Concordia",
    "Muisne",
    "Quinindé",
    "Rio Verde",
    "San Lorenzo",
    "San Mateo",
    "Sua",
    "Tabiazo",
    "Tachina",
    "Tonsupa",
    "Vuelta Larga"
  ],
  "Guayas": [
    "Alfredo Baquerizo Moreno",
    "Balao",
    "Balzar",
    "Boliche",
    "Bucay",
    "Chobo",
    "Colimes",
    "Coronel Marcelino Maridueña",
    "Daule",
    "Durán",
    "El Empalme",
    "El Piedrero",
    "El Triunfo",
    "General Antonio Elizalde",
    "Gral Villamil Playas",
    "Guayaquil",
    "Isidro Ayora",
    "Jujan",
    "La Puntilla",
    "Las Mercedes",
    "Laurel",
    "Limonal",
    "Lomas de Sargentillo",
    "Los Tintos",
    "Mariscal Sucre",
    "Milagro",
    "Naranjal",
    "Naranjito",
    "Nobol",
    "Palestina",
    "Pedro Carbo",
    "Progreso",
    "Roberto Astudillo",
    "Salitre",
    "Samborondón",
    "Santa Lucia",
    "Simon Bolivar",
    "Villa Nueva",
    "Yaguachi"
  ],
  "Imbabura": [
    "Alpachaca",
    "Andrade Marin",
    "Antonio Ante",
    "Atuntaqui",
    "Caranqui",
    "Chaltura",
    "Chorlavi",
    "Cotacachi",
    "El Olivo",
    "El Retorno",
    "Eugenio Espejo (Calpaqui)",
    "Gonzales Suárez",
    "Ibarra",
    "Imantag",
    "Imbaya (San Luis de Cobuendo)",
    "La Esperanza",
    "Las Golondrinas",
    "Natabuela",
    "Otavalo",
    "Peguche",
    "Pimampiro",
    "Quiroga",
    "San Antonio De Ibarra",
    "San Blas",
    "San Juan de Iluman",
    "San Miguel de Urcuquí",
    "San Pablo Del Lago",
    "San Roque",
    "Tumbabiro",
    "Urcuquí",
    "Yaguarcocha"
  ],
  "Loja": [
    "Alamor",
    "Cariamanga",
    "Catamayo",
    "Celica",
    "Chaguarpamba",
    "Espíndola",
    "Gonzanamá",
    "Loja",
    "Macará",
    "Olmedo",
    "Paltas",
    "Pindal",
    "Puyango",
    "Quilanga",
    "San Sebastian",
    "Saraguro",
    "Sozoranga",
    "Sucre",
    "Vilcabamba",
    "Zapotillo"
  ],
  "Los Ríos": [
    "Baba",
    "Babahoyo",
    "Buena Fé",
    "Caracol",
    "La Esperanza",
    "La Union (Valencia)",
    "La Unión (Babahoyo)",
    "Mocache",
    "Montalvo",
    "Palenque",
    "Pimocha",
    "Pueblo Viejo",
    "Quevedo",
    "Quinsaloma",
    "San Camilo",
    "San Carlos",
    "Urdaneta",
    "Valencia",
    "Ventanas",
    "Vinces",
    "Zapotal"
  ],
  "Manabí": [
    "Alhajuela",
    "Bahia de Caraquez",
    "Bolivar",
    "Calceta",
    "Canuto",
    "Chone",
    "Coaque",
    "Crucita",
    "El Carmen",
    "Flavio Alfaro",
    "Jama",
    "Jaramijó",
    "Jipijapa",
    "Junin",
    "Manga del Cura",
    "Manta",
    "Montecristi",
    "Olmedo",
    "Pajan",
    "Pedernales",
    "Pichincha",
    "Portoviejo",
    "Pueblo Nuevo",
    "Puerto Lopez",
    "Ricaurte",
    "Rocafuerte",
    "Río Chico",
    "San Antonio",
    "San Pedro de Suma",
    "San Placido",
    "San Vicente",
    "Santa Ana",
    "Sucre",
    "Tosagua",
    "Veinticuatro de Mayo"
  ],
  "Morona Santiago": [
    "General Proaño",
    "Gualaquiza",
    "Huamboya",
    "Limón Indanza",
    "Logroño",
    "Macas",
    "Morona",
    "Pablo Sexto",
    "Palora",
    "Río Blanco",
    "San Isidro",
    "San Juan Bosco",
    "Santiago de Méndez",
    "Sevilla don Bosco",
    "Sucúa",
    "Taisha",
    "Tiwintza"
  ],
  "Napo": [
    "Archidona",
    "Baeza",
    "Carlos Julio Arosemena",
    "Cotundo",
    "El Chaco",
    "Pano",
    "Puerto Misahualli",
    "Puerto Napo",
    "San Pablo de Ushpayacu",
    "Tena"
  ],
  "Orellana": [
    "Aguarico",
    "El Coca",
    "Enokanqui",
    "Francisco de Orellana",
    "Joya de los Sachas",
    "Lago San Pedro",
    "Loreto",
    "Puerto Francisco de Orellana",
    "San Carlos",
    "San Sebastian del Coca",
    "Unión Milagreña"
  ],
  "Pastaza": [
    "Arajuno",
    "Diez de Agosto",
    "Fátima",
    "Mera",
    "Pastaza",
    "Puyo",
    "Santa Clara",
    "Shell"
  ],
  "Pichincha": [
    "Alangasi",
    "Aloag",
    "Amaguaña",
    "Ayora",
    "Calderón",
    "Cayambe",
    "Checa",
    "Conocoto",
    "Cotogchoa",
    "Cumbayá",
    "El Quinche",
    "Guangopolo",
    "Guayllabamba",
    "La Armenia",
    "La Esperanza",
    "La Merced",
    "Llano Chico",
    "Llano Grande",
    "Machachi",
    "Miravalle",
    "Nayón",
    "Olmedo",
    "Otón",
    "Pedro Moncayo",
    "Pedro Vicente Maldonado",
    "Pifo",
    "Pintag",
    "Pomasqui",
    "Puembo",
    "Puerto Quito",
    "Pusuqui",
    "Quito",
    "Rumiñahui",
    "San Antonio De Pichincha",
    "San Jose de Morán",
    "San Juan De Calderón",
    "San Miguel de los Bancos",
    "San Rafael",
    "Sangolqui",
    "Tababela",
    "Tabacundo",
    "Tambillo",
    "Tocachi",
    "Tumbaco",
    "Tupigachi",
    "Yaruquí",
    "Zámbiza"
  ],
  "Santa Elena": [
    "Anconcito",
    "Ancón",
    "Ballenita",
    "La Libertad",
    "Muey",
    "Salinas",
    "Santa Elena"
  ],
  "Santo Domingo de los Tsáchilas": [
    "Abraham Calazacón",
    "Alluriquín",
    "Bombolí",
    "Chiguilpe",
    "La Concordia",
    "Luz De America",
    "Río Toachi",
    "Santo Domingo"
  ],
  "Sucumbíos": [
    "7 De Julio",
    "Cascales",
    "Cuyabeno",
    "El Eno",
    "General Farfán",
    "Gonzalo Pizarro",
    "Jambelí",
    "Jivino Verde",
    "Lago Agrio",
    "Nueva Loja.",
    "Pacayacu",
    "Putumayo",
    "Santa Cecilia",
    "Shushufindi",
    "Sucumbíos"
  ],
  "Tungurahua": [
    "Ambato",
    "Atahualpa (Chisalata)",
    "Baños de Agua Santa",
    "Cevallos",
    "Cuchibamba",
    "Huachi Grande",
    "Izamba",
    "Mocha",
    "Mundugleo",
    "Patate",
    "Picaigua",
    "Pinllo",
    "Quero",
    "Quinchicoto",
    "Quisapincha",
    "Salasaca",
    "San Pedro de Pelileo",
    "Santa Rosa (Ambato)",
    "Santiago de Píllaro",
    "Tisaleo",
    "Totoras",
    "Unamuncho"
  ],
  "Zamora Chinchipe": [
    "Centinela Del Condor",
    "Chinchipe",
    "Cumbaratza",
    "El Pangui",
    "Nangaritza",
    "Palanda",
    "Paquisha",
    "Timbara",
    "Yacuambi",
    "Yantzaza",
    "Zamora"
  ]
};


export function usesEcuadorCodCheckout(country: string): boolean {
  return country.toUpperCase() === "EC";
}

export function ecuadorProvincias(): string[] {
  return Object.keys(GEO_EC).sort((a, b) => a.localeCompare(b, "es"));
}

export function ecuadorCiudades(provincia: string): string[] {
  return GEO_EC[provincia] ?? [];
}
