import { withOtherPlace } from "./latam-other-place";

type PlaceTree = Record<string, Record<string, string[]>>;

const ZONAS_25 = Array.from({ length: 25 }, (_, i) => `Zona ${i + 1}`);

/** Well-known colonias / barrios / sectores for major LATAM delivery cities. */
const NEIGHBORHOODS: Record<string, PlaceTree> = {
  MX: {
    "Ciudad de México": {
      "Álvaro Obregón": [
        "Centro",
        "San Ángel",
        "San Ángel Inn",
        "Florida",
        "Santa Fe",
        "Las Águilas",
        "Olivar de los Padres",
        "Tlacopac",
        "Guadalupe Inn",
        "Merced Gómez",
      ],
      Azcapotzalco: [
        "Centro",
        "Clavería",
        "Nueva Santa María",
        "San Álvaro",
        "Pro-Hogar",
        "San Miguel Amantla",
      ],
      "Benito Juárez": [
        "Centro",
        "Del Valle",
        "Del Valle Norte",
        "Del Valle Sur",
        "Narvarte",
        "Nápoles",
        "Portales Norte",
        "Portales Sur",
        "Mixcoac",
        "Insurgentes Mixcoac",
        "San Pedro de los Pinos",
        "Nochebuena",
        "Piedad Narvarte",
        "Extremadura Insurgentes",
      ],
      Coyoacán: [
        "Centro",
        "Del Carmen",
        "Copilco Universidad",
        "Pedregal de Santo Domingo",
        "Ajusco",
        "Ciudad Jardín",
        "Pueblo de los Reyes",
        "Villa Coyoacán",
        "Santa Catarina",
      ],
      "Cuajimalpa de Morelos": [
        "Centro",
        "Santa Fe Cuajimalpa",
        "Contadero",
        "Lomas de Vista Hermosa",
        "San José de los Cedros",
      ],
      Cuauhtémoc: [
        "Centro",
        "Roma Norte",
        "Roma Sur",
        "Condesa",
        "Hipódromo",
        "Hipódromo Condesa",
        "Juárez",
        "Doctores",
        "Obrera",
        "San Rafael",
        "Santa María la Ribera",
        "Tabacalera",
        "Buenavista",
        "Guerrero",
        "Tepito",
        "Morelos",
        "Peralvillo",
        "Tránsito",
      ],
      "Gustavo A. Madero": [
        "Centro",
        "Lindavista",
        "Aragón",
        "Cuautepec",
        "Tepeyac Insurgentes",
        "Nueva Industrial Vallejo",
        "San Juan de Aragón",
      ],
      Iztacalco: ["Centro", "Agrícola Oriental", "Granjas México", "Paseos de Taxqueña"],
      Iztapalapa: [
        "Centro",
        "Santa Cruz Meyehualco",
        "Escuadrón 201",
        "Lomas Estrella",
        "Santa María Aztahuacán",
        "San Lorenzo Tezonco",
        "Cabeza de Juárez",
      ],
      "La Magdalena Contreras": ["Centro", "San Jerónimo Lídice", "San Nicolás Totolapan"],
      "Miguel Hidalgo": [
        "Centro",
        "Polanco",
        "Anzures",
        "Granada",
        "Irrigación",
        "Lomas de Chapultepec",
        "Tacubaya",
        "Escandón",
        "Observatorio",
        "Periodista",
        "Verónica Anzures",
      ],
      "Milpa Alta": ["Centro", "Villa Milpa Alta", "San Pedro Atocpan"],
      Tláhuac: ["Centro", "San Francisco Tlaltenco", "Santa Catarina Yecahuitzotl"],
      Tlalpan: [
        "Centro",
        "Pedregal de San Ángel",
        "Hueytitla",
        "Miguel Hidalgo Tlalpan",
        "Fuentes Brotantes",
        "Tlalpan Centro",
        "San Fernando",
      ],
      "Venustiano Carranza": [
        "Centro",
        "Jardín Balbuena",
        "Moctezuma",
        "Morelos",
        "Federal",
        "Aeronáutica Militar",
      ],
      Xochimilco: ["Centro", "Santa Cruz Acalpixca", "Santiago Tepalcatlalpan", "San Gregorio Atlapulco"],
    },
    Jalisco: {
      Guadalajara: [
        "Centro",
        "Americana",
        "Providencia",
        "Chapalita",
        "Oblatos",
        "Analco",
        "Santa Teresita",
        "Lafayette",
        "Jardines del Bosque",
        "Colonia San Juan",
        "Heliodoro Hernández Loza",
      ],
      Zapopan: [
        "Centro",
        "Ciudad Granja",
        "Valle Real",
        "Andares",
        "Tesistán",
        "Santa Margarita",
        "Las Fuentes",
        "El Colli",
      ],
      "Puerto Vallarta": ["Centro", "Zona Romántica", "Versalles", "Marina Vallarta", "Las Juntas"],
      Tlaquepaque: ["Centro", "San Pedro", "Las Pintas", "El Refugio"],
      Tonalá: ["Centro", "Loma Dorada", "Basilio Vadillo"],
    },
    "Nuevo León": {
      Monterrey: [
        "Centro",
        "San Jerónimo",
        "Cumbres",
        "Obispado",
        "Mitras Centro",
        "Mitras Norte",
        "Tec",
        "Contry",
        "Vista Hermosa",
        "Independencia",
      ],
      "San Pedro Garza García": [
        "Centro",
        "Del Valle",
        "Valle Oriente",
        "Fuentes del Valle",
        "Santa Engracia",
      ],
      Guadalupe: ["Centro", "Contry La Silla", "Las Puentes", "Santa Cruz"],
      Apodaca: ["Centro", "Huinalá", "Santa Rosa", "Pueblo Nuevo"],
      "San Nicolás de los Garza": ["Centro", "Anáhuac", "Las Puentes", "Casa Bella"],
      Escobedo: ["Centro", "Las Palmas", "Nueva Castilla"],
      "Santa Catarina": ["Centro", "La Fama", "El Lechugal"],
    },
    México: {
      Toluca: ["Centro", "Universidad", "Las Palomas", "Zinacantepec", "San Buenaventura"],
      Ecatepec: ["Centro", "Jardines de Morelos", "Las Américas", "Ciudad Azteca", "Valle de Aragón"],
      Naucalpan: ["Centro", "Satélite", "Echegaray", "Las Palmas", "San Mateo Nopala"],
      Tlalnepantla: ["Centro", "Valle Dorado", "San Javier", "Pirules"],
      Nezahualcóyotl: ["Centro", "Estado de México", "Metropolitana", "Benito Juárez"],
    },
    Puebla: {
      Puebla: [
        "Centro",
        "La Paz",
        "Angelópolis",
        "Las Ánimas",
        "Analco",
        "El Carmen",
        "San Manuel",
        "Maravillas",
      ],
    },
    "Baja California": {
      Tijuana: [
        "Centro",
        "Zona Río",
        "Playas de Tijuana",
        "La Mesa",
        "Otay",
        "Sánchez Taboada",
        "Hipódromo",
        "Cacho",
      ],
      Mexicali: ["Centro", "Nueva", "Industrial", "Esperanza", "Pueblo Nuevo"],
      Ensenada: ["Centro", "Chapultepec", "Maneadero", "El Sauzal"],
    },
    "Quintana Roo": {
      "Benito Juárez": [
        "Centro",
        "Zona Hotelera",
        "Supermanzana 22",
        "Supermanzana 50",
        "Puerto Juárez",
        "Alfredo V. Bonfil",
        "Región 94",
        "Tierra Maya",
      ],
      Solidaridad: [
        "Centro",
        "Playacar",
        "Gonzalo Guerrero",
        "Ejido",
        "Colonia Colosio",
        "Puerto Aventuras",
      ],
      "Puerto Morelos": ["Centro", "Supermanzana 2", "Villa Morelos"],
      Tulum: ["Centro", "Aldea Zama", "La Veleta", "Región 8"],
      Cozumel: ["Centro", "San Miguel", "Adolfo López Mateos"],
    },
    Yucatán: {
      Mérida: [
        "Centro",
        "García Ginerés",
        "Altabrisa",
        "Francisco de Montejo",
        "Chuburná",
        "Itzimná",
        "Montes de Amé",
        "Caucel",
      ],
    },
    "Querétaro de Arteaga": {
      Querétaro: ["Centro", "Juriquilla", "El Refugio", "Milénica", "Cimatario", "San Pablo"],
    },
    Guanajuato: {
      León: ["Centro", "La Martinica", "Valle del Campestre", "San Miguel", "Las Palmas", "Echeveste"],
    },
    Chihuahua: {
      "Ciudad Juárez": ["Centro", "Pronaf", "Las Palmas", "Partido Romero", "Morelos", "Riberas del Bravo"],
      Chihuahua: ["Centro", "San Felipe", "Nombre de Dios", "Campestre"],
    },
  },
  GT: {
    Guatemala: {
      Guatemala: ZONAS_25,
      Mixco: [
        "Centro",
        "Zona 1",
        "Zona 4",
        "Zona 7",
        "Zona 8",
        "El Milagro",
        "Lo de Bran",
        "San Cristóbal",
        "Landívar",
      ],
      "Villa Nueva": [
        "Centro",
        "Zona 1",
        "Zona 4",
        "Zona 12",
        "Bárcenas",
        "El Frutal",
        "Ciudad Real",
      ],
      Petapa: ["Centro", "Zona 1", "Villa Hermosa", "San Miguel Petapa"],
      "Villa Canales": ["Centro", "Boca del Monte", "Santa Elena Barillas"],
      "Santa Catarina Pinula": ["Centro", "Cayalá", "Puerta Parada", "El Carmen"],
      Chinautla: ["Centro", "Santa Cruz Chinautla", "Jocotales"],
      Amatitlán: ["Centro", "El Llano", "El Naranjo"],
    },
    Sacatepéquez: {
      "Antigua Guatemala": ["Centro", "San Felipe de Jesús", "Jocotenango", "Ciudad Vieja"],
    },
    Quetzaltenango: {
      Quetzaltenango: ["Centro", "Zona 1", "Zona 3", "Zona 5", "La Esperanza"],
    },
  },
  HN: {
    "Francisco Morazán": {
      "Distrito Central": [
        "Centro",
        "Comayagüela",
        "El Hatillo",
        "Kennedy",
        "Miraflores",
        "Lomas del Guijarro",
        "Lomas del Mayab",
        "San Miguel",
        "El Pedregal",
        "La Granja",
        "El Chile",
        "Suyapa",
        "Cerro Grande",
        "Hato de Enmedio",
        "Florencia",
      ],
    },
    Cortés: {
      "San Pedro Sula": [
        "Centro",
        "Río de Piedras",
        "Colonia Satélite",
        "Colonia Universidad",
        "Colonia Trejo",
        "Colonia Moderna",
        "Chamelecón",
        "Cofradía",
        "La Lima",
      ],
      Choloma: ["Centro", "La Mora", "El Carmen", "Río Nance"],
      "Puerto Cortés": ["Centro", "Cieneguita", "Travesía", "Bajamar"],
    },
    Atlántida: {
      "La Ceiba": ["Centro", "La Isla", "Sambo Creek", "El Pino", "La Merced"],
      Tela: ["Centro", "Lancetilla", "Triunfo de la Cruz"],
    },
    "Islas de la Bahía": {
      Roatán: ["Coxen Hole", "West End", "West Bay", "French Harbour", "Punta Gorda"],
      Utila: ["Centro", "East Harbour"],
      Guanaja: ["Centro", "Savannah Bight"],
    },
  },
  SV: {
    "San Salvador": {
      "San Salvador": [
        "Centro",
        "Escalón",
        "San Benito",
        "Colonia Médica",
        "San Francisco",
        "Flor Blanca",
        "Miravalle",
        "Santa Elena",
        "Zacamil",
        "Monserrat",
        "Layco",
        "Centro Histórico",
      ],
      Soyapango: ["Centro", "Santa Lucía", "Santo Tomás", "Colonia Guadalupe"],
      Mejicanos: ["Centro", "San Ramón", "Cuscatancingo"],
      "Santa Tecla": ["Centro", "El Carmen", "San José", "Las Delicias"],
      Apopa: ["Centro", "San Nicolás", "Guayote"],
    },
    "La Libertad": {
      "Santa Tecla": ["Centro", "El Carmen", "San José", "Las Delicias", "Las Colinas"],
      "Antiguo Cuscatlán": ["Centro", "Santa Elena", "Nuevo Cuscatlán", "La Skina"],
      "La Libertad": ["Centro", "Zaragoza", "El Sunzal", "El Tunco"],
    },
    "Santa Ana": {
      "Santa Ana": ["Centro", "El Palmar", "San Sebastián", "Altos de Santa Ana"],
    },
    "San Miguel": {
      "San Miguel": ["Centro", "Ciudad Pacífica", "Belén", "San Rafael"],
    },
  },
  NI: {
    Managua: {
      Managua: [
        "Centro",
        "Bello Horizonte",
        "Ciudad Jardín",
        "Las Colinas",
        "Altamira",
        "Reparto Schick",
        "Villa Reconciliación",
        "Distrito I",
        "Distrito II",
        "Distrito III",
        "Distrito IV",
        "Distrito V",
        "Distrito VI",
        "Distrito VII",
        "Linda Vista",
        "San Judas",
        "Villa Fontana",
        "Las Piedrecitas",
      ],
      Tipitapa: ["Centro", "Ciudad Sandino Sur", "San Benito"],
      "Ciudad Sandino": ["Centro", "Zona 1", "Zona 4", "Pista Suburbana"],
    },
    León: {
      León: ["Centro", "Sutiava", "Guadalupe", "Laborío", "Zaragüeta"],
    },
    Granada: {
      Granada: ["Centro", "La Polvora", "El Recreo", "Palos Negros"],
    },
  },
  DO: {
    "Distrito Nacional": {
      "Santo Domingo de Guzmán": [
        "Gazcue",
        "Naco",
        "Piantini",
        "Bella Vista",
        "Ensanche La Fe",
        "Villa Juana",
        "Villa Consuelo",
        "Cristo Rey",
        "Los Cacicazgos",
        "Mirador Norte",
        "Mirador Sur",
        "Zona Colonial",
        "San Carlos",
        "Villa Francisca",
        "Ensanche Naco",
        "Los Prados",
        "Arroyo Hondo",
      ],
    },
    "Santo Domingo": {
      "Santo Domingo Este": [
        "Los Mina",
        "Alma Rosa",
        "Villa Duarte",
        "Cancino",
        "San Isidro",
        "Invivienda",
        "Las Américas",
        "Mendoza",
      ],
      "Santo Domingo Norte": ["Villa Mella", "Sabana Perdida", "La Victoria", "San Felipe"],
      "Santo Domingo Oeste": ["Herrera", "Buenos Aires", "Las Caobas", "Hato Nuevo"],
      "Los Alcarrizos": ["Centro", "Pantoja", "Palave"],
      "Boca Chica": ["Centro", "Andrés", "La Caleta"],
    },
    Santiago: {
      Santiago: [
        "Centro",
        "Los Jardines",
        "Cerros de Gurabo",
        "Pueblo Nuevo",
        "La Trinitaria",
        "Ensanche Bermúdez",
        "Villa Olga",
        "Cienfuegos",
      ],
    },
    "La Altagracia": {
      Higüey: ["Centro", "La Otra Banda", "Verón"],
      "Verón-Punta Cana": ["Punta Cana", "Bávaro", "Verón", "Cap Cana", "Uvero Alto", "Cabeza de Toro"],
      "Punta Cana": ["Bávaro", "Cortecito", "El Cortecito", "Arena Gorda", "Cap Cana"],
    },
    "Puerto Plata": {
      "Puerto Plata": ["Centro", "Costámbar", "Playa Dorada", "Cofresí"],
      Sosúa: ["Centro", "El Batey", "Los Charamicos", "Cabarete"],
      Cabarete: ["Centro", "Kite Beach", "Encuentro"],
    },
  },
  EC: {
    Pichincha: {
      Quito: [
        "Centro Histórico",
        "La Mariscal",
        "La Carolina",
        "González Suárez",
        "Cumbayá",
        "Tumbaco",
        "Los Chillos",
        "El Inca",
        "Cotocollao",
        "Carcelén",
        "Quitumbe",
        "El Condado",
        "La Kennedy",
        "Guápulo",
      ],
    },
    Guayas: {
      Guayaquil: [
        "Centro",
        "Urdesa",
        "Samborondón",
        "Alborada",
        "Sauces",
        "Mapasingue",
        "Ceibos",
        "Kennedy Norte",
        "Via a la Costa",
        "Bastión Popular",
        "Fertisa",
        "Las Peñas",
      ],
    },
    "Azuay": {
      Cuenca: ["Centro", "El Ejido", "Yanuncay", "Totoracocha", "Ricaurte", "Baños"],
    },
    Manabí: {
      Manta: ["Centro", "Tarqui", "El Palmar", "Los Esteros", "Murciélago"],
      Portoviejo: ["Centro", "Picoazá", "Colón", "San Pablo"],
    },
  },
  CR: {
    "San José": {
      "San José": [
        "Carmen",
        "Merced",
        "Hospital",
        "Catedral",
        "Zapote",
        "San Francisco de Dos Ríos",
        "Uruca",
        "Mata Redonda",
        "Pavas",
        "Hatillo",
        "San Sebastián",
      ],
      Escazú: ["Escazú", "San Antonio", "San Rafael"],
      Desamparados: ["Desamparados", "San Miguel", "San Juan de Dios", "San Rafael Arriba"],
    },
  },
  AR: {
    Córdoba: {
      Córdoba: [
        "Centro",
        "Nueva Córdoba",
        "Güemes",
        "Alberdi",
        "General Paz",
        "Cerro de las Rosas",
        "Barrio Jardín",
      ],
    },
    "Santa Fe": {
      Rosario: ["Centro", "Pichincha", "Fisherton", "Echesortu", "Luis Agote", "Alberdi"],
    },
    Mendoza: {
      Mendoza: ["Centro", "Godoy Cruz", "Las Heras", "Guaymallén", "Chacras de Coria"],
    },
  },
};

function lookupOverlay(country: string, l1: string, l2: string): string[] {
  return NEIGHBORHOODS[country]?.[l1]?.[l2] ?? [];
}

export function mergePlaceOptions(
  country: string,
  l1: string,
  l2: string,
  base: string[] = []
): string[] {
  const overlay = lookupOverlay(country, l1, l2);
  const keepBaseCentro = overlay.length === 0;
  const merged = [
    ...new Set([
      ...overlay,
      ...base.filter((name) => keepBaseCentro || name !== "Centro" || overlay.includes("Centro")),
    ]),
  ];
  if (!merged.length) merged.push("Centro");
  merged.sort((a, b) => a.localeCompare(b, "es"));
  return withOtherPlace(merged);
}
